name: viserpay
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  another_flushbar: ^1.12.30
  animated_text_kit: ^4.2.2
  awesome_dialog: ^3.1.0
  cached_network_image: ^3.3.0
  carousel_slider: ^5.0.0
  circular_countdown_timer: ^0.2.3
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  dots_indicator: ^3.0.0
  dotted_border: ^2.0.0+2
  expandable_page_view: ^1.0.17
  fast_contacts: ^4.0.0
  file_manager: ^1.0.2
  file_picker: ^6.1.1
  firebase_analytics: ^10.7.4
  firebase_core: ^2.24.2
  firebase_core_platform_interface: ^5.0.0
  firebase_messaging: ^14.7.8
  flutter:
    sdk: flutter
  flutter_advanced_switch: ^3.0.1
  flutter_inappwebview: ^5.7.2+3
  flutter_local_notifications: ^17.1.2
  flutter_secure_storage: ^9.0.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.4
  flutter_widget_from_html: ^0.14.9
  get: ^4.6.5
  http: ^1.1.2
  im_stepper: ^1.0.1+1
  image_gallery_saver: ^2.0.3
  image_picker: ^1.0.4
  intl: ^0.17.0
  local_auth: ^2.1.7
  lottie: ^2.3.1
  octo_image: ^2.0.0
  open_file: ^3.3.2
  path_provider: ^2.0.9
  permission_handler: ^11.1.0
  pin_code_fields: ^8.0.1
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.0.0
  share_plus: ^7.2.1
  shared_preferences: ^2.0.13
  shimmer: ^3.0.0
  simple_animations: ^5.0.2
  super_tooltip: ^2.0.7
  url_launcher: ^6.2.2
  vibration: ^1.8.4
  flutter_exit_app: ^1.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  archive: ^3.6.1 # Tambahkan baris ini

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo/
    # - assets/images/onboard/
    - assets/icon/
    - assets/img/
    - assets/animation/

  fonts:
    - family: Rajdhani
      fonts:
        - asset: assets/fonts/Rajdhani-Bold.ttf
        - asset: assets/fonts/Rajdhani-Light.ttf
        - asset: assets/fonts/Rajdhani-Medium.ttf
        - asset: assets/fonts/Rajdhani-Regular.ttf
        - asset: assets/fonts/Rajdhani-SemiBold.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Thin.ttf
